apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: application02
  name: application02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: application02
    spec:
      containers:
      - image: yeasy/simple-web:latest
        name: simple-web
        resources: {}
status: {}
